name: SimpleUtils
authors: [Mooy1, LobbyTech-MC, ybw0014]
description: Simple utilities items for slimefun, translated by LobbyTech-MC, modified by ybw0014
website: https://github.com/ybw0014/SimpleUtils
main: io.github.mooy1.simpleutils.SimpleUtils
depend: [Slimefun]
version: ${project.version}
api-version: 1.16

commands:
  simpleutils:
    description: Do /simpleutils help for a list of commands
    usage: /simpleutils <subcommand>
    aliases: [ su, simple ]
